name: Windows Builder

on: [push, pull_request]

jobs:
  windows-build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1.1
      - name: Install Npcap
        run: |
          Invoke-WebRequest https://npcap.com/dist/npcap-sdk-1.13.zip -OutFile ../npcap-sdk.zip
          Expand-Archive ../npcap-sdk.zip -DestinationPath ../npcap-sdk
      - name: Build 64-bit
        shell: cmd
        run: |
          .\win32\msvcbuild.bat x64
